FROM debian:latest

RUN apt update

# 安装要用到的工具
RUN apt install git npm wget -y

# 安装 nodejs 安装器
RUN npm i -g n

# 安装 nodejs stable
RUN n stable

# 刷新缓存
RUN hash -r

# 克隆koishi-bp
RUN git clone https://github.com/koishijs/boilerplate

# 修改端口
RUN sed -i 's/port: 5140/port: 7860/g' /boilerplate/koishi.yml

# 避免 go-cqhttp 安装失败
RUN mkdir /.local
RUN chmod -R 777 /.local

# 安装依赖
RUN cd /boilerplate; corepack enable; yarn install

# 修改权限防止抱错
RUN chmod -R 777 /boilerplate

# 设置工作目录
WORKDIR "/boilerplate"

# 设置启动命令
CMD ["yarn", "start"]