FROM debian:latest

RUN apt update

# 安装 chromium 及要用到的工具
RUN apt install git npm wget -y

# 安装 nodejs 安装器
RUN npm i -g n

# 安装 nodejs stable
RUN n stable

# 刷新缓存
RUN hash -r

# 克隆koishi-bp
RUN git clone https://github.com/initialencounter/koimux_bot

# 修改端口
RUN sed -i 's/port: 5140/port: 7860/g' /koimux_bot/koishi.yml

# 安装依赖
RUN cd /koimux_bot; npm i

# 修改权限防止抱错
RUN chmod -R 777 /koimux_bot
RUN mkdir /.npm
RUN chmod -R 777 /.npm
RUN mkdir /.local
RUN chmod -R 777 /.local

# 设置工作目录
WORKDIR "/koimux_bot"

# 设置启动命令
CMD ["npm", "start"]