name: Deploy VitePress Docs to GitHub Pages

on:
  push:
    branches:
      - master  # 在 master 分支推送时触发
    paths:
      - 'docs/**' # 仅在 docs 目录下的文件发生更改时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master  # 检出 master 分支
          path: master  # 检出到 master 目录

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache Dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: master/node_modules
          key: deps-${{ runner.os }}-${{ hashFiles('master/yarn.lock') }}

      - name: Install Dependencies
        run: |
          cd master
          yarn install # 不使用 --frozen-lockfile，允许更新 yarn.lock

      - name: Build VitePress Site
        run: cd master && yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: master/docs/.vitepress/dist
